
stages:
  - build
  - test
  - deploy

build:
  image: maven:3.8.4-openjdk-17
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/MockProject-0.0.1-SNAPSHOT.jar

test:
  image: maven:3.8.4-openjdk-17
  script:
    - mvn test

deploy:
  stage: deploy
  script:
    - az webapp deployment source config-zip -g Test -n freshclassmanagement --src target/MockProject-0.0.1-SNAPSHOT.jar