
stages:
  - test
  - deploy

test-all:
  stage: test
  tags: [windows]
  except:
    - main
  script:
    - mvn clean install

test-unit:
  stage: test
  tags: [ windows ]
  only:
    - main
  script:
    - mvn clean package
    - cp target/MockProject-0.0.1-SNAPSHOT.jar MockProject-0.0.1-SNAPSHOT.jar
  artifacts:
    name: backend-social-network
    expire_in: 1 week
    paths:
      - MockProject-0.0.1-SNAPSHOT.jar

deploy:
  stage: deploy
  needs: [test-unit]
  only:
    - main
  script:
    - ls MockProject-0.0.1-SNAPSHOT.jar