
stages:
  - build
  - test

build:
  image: maven:3.8.4-openjdk-17
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/MockProject-0.0.1-SNAPSHOT.jar

test:
  image: maven:3.8.4-openjdk-17
  script:
    - mvn test

